version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: service-redis
    command: redis-server --requirepass rootroot
    ports:
      - "16377:6379"
    volumes:
      - ./data:/data


# docker-compose up -d
# docker ps